USE QLSVNhom
GO

-- Xóa dữ liệu theo thứ tự FK
DELETE FROM BANGDIEM;
DELETE FROM SINHVIEN;
DELETE FROM LOP;

-- Xóa asymmetric key của từng nhân viên trước khi xóa nhân viên
DECLARE @MANV VARCHAR(20);
DECLARE cur CURSOR FOR SELECT MANV FROM NHANVIEN;
OPEN cur;
FETCH NEXT FROM cur INTO @MANV;
WHILE @@FETCH_STATUS = 0
BEGIN
    DECLARE @SQL NVARCHAR(MAX);
    SET @SQL = 'DROP ASYMMETRIC KEY ' + QUOTENAME(@MANV);
    EXEC sp_executesql @SQL;
    FETCH NEXT FROM cur INTO @MANV;
END
CLOSE cur;
DEALLOCATE cur;

DELETE FROM NHANVIEN;
DELETE FROM HOCPHAN;

PRINT N'Đã xóa toàn bộ dữ liệu!';
GO
